장바구니 step1
soyi47/ts-shopping-cart pull request #1
Opened 2024-04-28 06:17 UTC by soyi47

# 장바구니 - step1

## 🎯 요구사항
- 헤더
  - [x] 사이트 로고를 클릭하면 메인 페이지로 이동한다.
  - [x] 장바구니, 주문목록 버튼을 누르면 준비 중이라는 메세지를 보여준다.
- 상품 목록 페이지
  - [x] 메인 페이지로 상품 목록 페이지를 보여준다.
    - [x] 상품 목록 정보는 서버에서 가져온다.
      - [x] 로딩이 끝나면 상품 목록을 띄운다.
    - [x] 상품 목록 아이템에는 상품 이미지, 상품 이름, 상품 가격, 장바구니 담기 버튼이 있다.
    - [x] 장바구니 담기 버튼을 클릭하면 준비 중이라는 메세지를 띄운다.
    - [x] 상품 목록 아이템이 없으면 비었다는 내용의 메세지를 보여준다.
    - [x] 상품 카드를 클릭하면, 해당 상품 상세 페이지로 이동한다.
- 상품 상세 페이지
  - [x] 상품 id에 따른 상품 정보를 보여준다.
  - [x] 장바구니 담기 버튼을 클릭하면 준비 중이라는 메세지를 띄운다.

## 소감 및 공유
next + vanilla-extract 사용하여 구현해봤습니다
msw 사용하려 했으나 설정 이슈로 api에 더미 데이터 바로 넣었어요 🥲

샐선생님 리뷰 잘 부탁드립니다. 🫡

2024-05-09 14:04 UTC, liswktjs requested changes
수고하셨습니다 소피아 🐄 👏

Next page router 방식을 사용해보셨군요 
next로 한 번 router를 편하게 하다 보면 익숙해져서 react router 방식이 어색해집니다  

next로 하는 김에 더 적용해보면 좋을 것 같은 점들 코멘트로 남겼습니다 
한 번 확인 부탁드려요 👍

2024-05-09 14:04 UTC, liswktjs commented on src/pages/api/products/[id].ts
> +      productPrice: 11029384,
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ광기가 느껴졌어요 
![스크린샷 2024-05-09 오후 10 38 00](https://github.com/soyi47/ts-shopping-cart/assets/60773373/bab9f285-578f-4a9d-87a8-97046b6a57b5)

2024-05-09 14:04 UTC, liswktjs commented on src/pages/products/[id].css.ts
> +import { style } from "@vanilla-extract/css";
참고로 page router를 사용할 때  폴더로 묶어서 router 대상에서 제외하고 싶을 때에는 
https://nextjs.org/docs/getting-started/project-structure#route-groups-and-private-folders 
```
(folder) | Group routes without affecting routing
_folder | Opt folder and all child segments out of routing
```

요런 방법도있습니다 css 선언방식이 잘못된건 아닌데 한번 생각나서 코멘트 달아봤습니다 키키

2024-05-09 14:04 UTC, liswktjs commented on src/pages/products/[id].tsx
> +import * as styles from "./[id].css";
valina extract 사용은 또 처음 보네여 이렇게 보니 styleX와 비슷한 측면도 있는 것 처럼 보이네요
ssr도 지원이 되는군요

2024-05-09 14:04 UTC, liswktjs commented on src/pages/index.tsx
> +  const { id } = ctx.query;
여기 id값이 사용되지 않고 잇는 것 같습니다

2024-05-09 14:04 UTC, liswktjs commented on src/pages/index.tsx
> +    <div>
이곳 div tag도 없어도 될 것 같습니다!

2024-05-09 14:04 UTC, liswktjs commented on src/components/Header.tsx
> +      <nav>
오 semantic하게 tag를 잘 작성해주셨네요 👍

2024-05-09 14:04 UTC, liswktjs commented on src/components/ProductListItem.css.ts
> +  height: 440,
오호 vanilla extract은 px이라고 따로 지정을 안해줘도 되나 보군요

2024-05-09 14:04 UTC, liswktjs commented on src/components/ProductListItem.tsx
> +        <img className={styles.thumbnail} src={productThumbnail} alt="" />
Next의 Image 컴포넌트를 한 번 사용해보시죠 
https://nextjs.org/docs/pages/api-reference/components/image

2024-05-12 15:18 UTC, soyi47 reviewed
샐리 리뷰 감사합니다! 💖

제안사항 반영해보았어요. 확인 부탁드립니다. 🙇‍♀️

2024-05-12 15:18 UTC, soyi47 commented on src/components/ProductListItem.css.ts
> +  height: 440,
https://vanilla-extract.style/documentation/styling/#unitless-properties

맞습니다 자동으로 px 단위를 값에 붙여줘요!

2024-05-12 15:18 UTC, soyi47 commented on src/components/ProductListItem.tsx
> +        <img className={styles.thumbnail} src={productThumbnail} alt="" />
https://nextjs.org/docs/app/building-your-application/optimizing/images

알아서 최적화 해주는 게 많군요? 굿! 👍 

[refactor: next/Image 적용](https://github.com/soyi47/ts-shopping-cart/pull/1/commits/d9ae8aad7e384902626af4ef42242e961f6ec78c)

2024-05-12 15:18 UTC, soyi47 commented on src/pages/index.tsx
> +  const { id } = ctx.query;
로컬에서 지워놓고 안 올려뒀네요! 샐리 매의 눈이군요 👀

[refactor: 불필요한 문장 제거](https://github.com/soyi47/ts-shopping-cart/pull/1/commits/ddc712edd169535175ecd794b4251120851909ac)

2024-05-12 15:18 UTC, soyi47 commented on src/pages/products/[id].css.ts
> +import { style } from "@vanilla-extract/css";
새로 배워갑니다 샐리 감사합니다! 👍👍👍

2024-05-12 15:18 UTC, soyi47 commented on src/pages/products/[id].tsx
> +import * as styles from "./[id].css";
스타일 정의하는 방식도 얼핏 비슷한 것 같네요. 저도 다음엔 styleX 사용해봐야겠어요.

2024-06-02 15:16 UTC, liswktjs approved these changes
소피아 수고 많으셨습니다! 
하하 시간이 늦어져서 이제서야 approve를 하네요 😅
죄송합니다 🥲

이번에 리뷰하면서 소피아 덕분에 valina extract도 찍먹 할 수 있었네요 👍
Next가 생각보다 지원하고 있는 기능들이 많아서 개발할 때 많은 도움이 된답니다 하하 
같이 Next의 세계로 가시죠

2024-06-09 12:51 UTC, merged